### PR TITLE
Restore tests/test_proxy_connect.py

### PR DESCRIPTION
**Pull request by Gallaecio**
May need to increase the build number of #48 or here depending on which pull request gets merged first.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by wRAR — APPROVED** [review]

**Comment by wRAR** [comment]
What was changed to allow us to run this test again?

**Comment by Gallaecio** [comment]
Probably nothing, I’m just waiting to see what breaks and see how we can fix it :slightly_smiling_face:

**Comment by Gallaecio** [comment]
:tada:

**Comment by Gallaecio** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
