### PR TITLE
2.7.0

### PR DESCRIPTION
**Pull request by wRAR**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wRAR** [comment]
@conda-forge-admin, please rerender

**Comment by Gallaecio** [comment]
Weird errors.

**Comment by wRAR** [comment]
I was able to reproduce the failure locally with PyCharm (but not with pytest), a first run of the test creates the images in ./tests/store-uri and subsequent runs read those instead of running `download_func` etc. Bisecting points at https://github.com/scrapy/scrapy/commit/5c586d78f0e1c5b66358ed644bb6e528ad4b062b , before it the dir was empty, after it the dir contains images.

**Comment by wRAR** [comment]
While this is the underlying problem, it's only visible in PyCharm (i.e. with `python3 -m unittest`) because pytest normally creates such files in a temporary directory different for each run and for each test (`/tmp/pytest-of-wrar/pytest-8/test_file_downloaded_called0`). Conda CI runs pytest too, but apparently this feature doesn't work in the same way for some reason, and I don't see any plugins or configuration in the log that could change it.

**Pull request merged**
