### PR TITLE
remove python version constraint

### LINKED ISSUE #62: Support python 3.9 and 3.10
Scrapy 2.6.0 has offical Python 3.10 support, but in conda we only have 3.8 . @Gallaecio

### PR DESCRIPTION
**Pull request by holymonson**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

--- 

Close #62. This one seems fine. @Gallaecio

### CODE REVIEW

**Comment by holymonson** [comment]
@Gallaecio mitmproxy>=6 requires Python >=3.8, while mitmproxy==5.3.0 fails tests on python==3.7. Should we skip those tests on python3.7?

**Comment by wRAR** [comment]
The fix for the old mitmproxy is pinning old markupsafe like in #60

**Comment by holymonson** [comment]
FYI, mitmproxy<5.3.0 fails on python 3.9.

**Comment by holymonson** [comment]
@Gallaecio checks are all good, would you review this?

**Review by Gallaecio — APPROVED** [review]
Looks good to me, great work!

**Review by wRAR — APPROVED** [review]

**Pull request merged**
