### PR TITLE
scrapy v1.7.2

### PR DESCRIPTION
**Pull request by Gallaecio**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Change summary:
* Upgrade to 1.7.2
* Update Scrapy dependencies according to `setup.py` changes since 1.5.0
* Switch from simple import tests to running the actual tests from Scrapy, skipping tests that fail on Windows or macOS, which are likely due to test failures rather than Scrapy bugs. We’ll need to look into those later in Scrapy itself.

Closes #21, closes #22, closes #23, closes #25

### CODE REVIEW

**Comment by Gallaecio** [comment]
@conda-forge-admin, please rerender

**Comment by Gallaecio** [comment]
@conda-forge-admin, please rerender

**Comment by Gallaecio** [comment]
@conda-forge ping

**Comment by Gallaecio** [comment]
@rmax @redapple The changes should be ready now, please feel free to review. Thanks!

**Comment by rmax** [comment]
Looks good to me. Thanks!

**Pull request merged**
