### PR TITLE
Rebuild for Python 3.11

### PR DESCRIPTION
**Pull request by wRAR**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wRAR** [comment]
@conda-forge-admin, please rerender

**Comment by wRAR** [comment]
(automatic rebuilding failed with "Error: not solvable (bot CI job): main: ['osx_arm64_python3.11.____cpython: Encountered problems while solving:\n - package bpython-0.20.1-py38hca03da5_1 requires python >=3.8,<3.9.0a0, but none of the providers can be installed\n']")

**Comment by wRAR** [comment]
OK, this doesn't build because of https://github.com/scrapy/scrapy/issues/5750

**Comment by holymonson** [comment]
> (automatic rebuilding failed with "Error: not solvable (bot CI job): main: ['osx_arm64_python3.11.____cpython: Encountered problems while solving:\n - package bpython-0.20.1-py38hca03da5_1 requires python >=3.8,<3.9.0a0, but none of the providers can be installed\n']")

This issue should have been fixed by https://github.com/conda-forge/bpython-feedstock/pull/23, we are expecting cf-bot will file a new PR for 3.11-rebuild tomorrow.

**Pull request closed without merging**
