### PR TITLE
fix: restore scrapy entrypoint

### LINKED ISSUE #37: Issue with conda-forge scrapy>1.6.0 on Windows
Issue: Already reported in the scrapy repo: https://github.com/scrapy/scrapy/issues/4289

When installing scrapy from conda-forge, no error appears during the process but when trying to run `scrapy` the following error appears: 

```Fatal error in launcher: Unable to create process using '"d:\bld\scrapy_1584555945006\_h_env\python.exe"  "C:\Users\benoi\anaconda3\envs\scrapy\Scripts\scrapy.exe" ': The system cannot find the file specified.```

I have no D: drive on my machine.
As reported in the bug on the scrapy repo, installing withthe previous 1.6.0 version with `conda install -c conda-forge scrapy=1.6.0` works.

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at C:\Users\benoi\anaconda3\envs\scrapy:
#
# Name                    Version                   Build  Channel
astroid                   2.3.3                    py38_0
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
automat                   20.2.0                     py_0    conda-forge
bcrypt                    3.1.7            py38h9de7a3e_1    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38ha419a9e_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
cryptography              2.8              py38hb32ad35_1    conda-forge
cssselect                 1.1.0                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.0            py38h32f6830_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
incremental               17.5.0                     py_0    conda-forge
isort                     4.3.21                   py38_0
lazy-object-proxy         1.4.3            py38he774522_0
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
libxslt                   1.1.33               heafd4d3_0    conda-forge
lxml                      4.5.0            py38h7b22a32_1    conda-forge
mccabe                    0.6.1                    py38_1
more-itertools            8.2.0                      py_0    conda-forge
openssl                   1.1.1f               hfa6e2cd_0    conda-forge
packaging                 20.1                       py_0    conda-forge
parsel                    1.5.2                    py38_0
pip                       20.0.2                     py_2    conda-forge
pluggy                    0.13.1                   py38_0    conda-forge
protego                   0.1.16                     py_0    conda-forge
py                        1.8.1                      py_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pydispatcher              2.0.5                      py_1    conda-forge
pyhamcrest                2.0.2                      py_0    conda-forge
pylint                    2.4.4                    py38_0
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pytest                    5.4.1            py38h32f6830_0    conda-forge
pytest-runner             5.2                        py_0    conda-forge
python                    3.8.2           h5fd99cc_5_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pywin32                   227              py38hfa6e2cd_0    conda-forge
queuelib                  1.5.0                    py38_0
scrapy                    1.6.0                    py38_0
service_identity          18.1.0                     py_0    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
twisted                   20.3.0           py38h9de7a3e_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_1    conda-forge
w3lib                     1.20.0                     py_0    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
wrapt                     1.12.1           py38he774522_1
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zope.interface            5.0.2            py38h9de7a3e_0    conda-forg

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : scrapy
    active env location : C:\Users\benoi\anaconda3\envs\scrapy
            shell level : 2
       user config file : C:\Users\benoi\.condarc
 populated config files : C:\Users\benoi\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages :
       base environment : C:\Users\benoi\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\benoi\anaconda3\pkgs
                          C:\Users\benoi\.conda\pkgs
                          C:\Users\benoi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\benoi\anaconda3\envs
                          C:\Users\benoi\.conda\envs
                          C:\Users\benoi\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by rmax**
Attempt to fix #37 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Gallaecio** [comment]
It may be better to work on the tests separately.

Also, we probably need to handle https://github.com/scrapy/scrapy/pull/4458 before we can consider looking for 100% test passes on Windows here.

**Comment by rmax** [comment]
@Gallaecio indeed. I will try to add skip flag to all tests dynamically to run them but don't fail, so at least we can see all the failures in the build log while still building the package for win.

**Comment by rmax** [comment]
Restored the `scrapy version` test :tada:
Pipelines_-_Run_20200526_2_logs

**Comment by rmax** [comment]
FYI, osx build failed on master for `py3.8`. Given there is already package for the same version, it's not critical to fix it right now.

**Pull request merged**
