### PR TITLE
remove several import tests that were showing deprecation warnings

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by rmax** [comment]
Looks like it's missing `setuptools` as runtime dependency. Previous builds installed the dependency automatically so perhaps a dependency no longer depends on `setuptools`.

**Comment by msarahan** [comment]
@rmax this is a very common problem in recipes.  setuptools has commonly been included as a python dependency with some pretty nasty hacks in conda.  People thus often forget to include it as a run dependency, and then packages can break down the line when people don't have that conda hack enabled.

If scrapy does indeed need setuptools at runtime (for example, it uses pkg_resources), I strongly advise you to add it in meta.yaml's run requirements.  I can do that in this PR if you really want me to.

**Comment by rmax** [comment]
@msarahan Yes, scrapy depends on pkg_resources. See https://github.com/scrapy/scrapy/blob/master/scrapy/cmdline.py#L6

Could you update the PR and include `setuptools` as runtime dependency?

**Comment by redapple** [comment]
@msarahan , @rmax , how does it look?
I wanted to have this before upgrading to Scrapy 1.5

**Comment by rmax** [comment]
Looks good to me!

**Pull request merged**
