### PR TITLE
Scrapy 2.0.0

### PR DESCRIPTION
**Pull request by Gallaecio**
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0`
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Gallaecio** [comment]
@conda-forge-admin, please rerender

**Comment by Gallaecio** [comment]
@conda-forge-admin, please rerender

**Comment by Gallaecio** [comment]
I guess we will need to create a recipe for Protego first.

**Comment by synapticarbors** [comment]
I merged the PR for Protego, so feel free to re-trigger the build.

**Comment by rmax** [comment]
Openssl giving headaches as usual 😅

**Comment by Gallaecio** [comment]
Almost there… :sweat_smile:

**Comment by rmax** [comment]
@Gallaecio BTW, if you want to get 2.0 out of the door for non-win platforms, you can add the `skip` rule for windows, get it merge, and then work on the win build and increase the build version.

**Comment by Gallaecio** [comment]
I may skip tests altogether, as we know it works, the issue is that tests do not pass due to version conflicts and compilation issues which should not affect users.

So yes, I should just get the release out, and create a backlog issue to deal with the test issues.

**Comment by Gallaecio** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
