### PR TITLE
temporarily restrict w3lib

### PR DESCRIPTION
**Pull request by holymonson**
Should be released after https://github.com/scrapy/scrapy/pull/5756 released.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by holymonson** [comment]
@conda-forge-admin, please rerender

**Comment by holymonson** [comment]
@wRAR The fails seems not related to w3lib, could you figure out why?

**Comment by wRAR** [comment]
@holymonson there are several unrelated test failures in Scrapy, some of them are fixed in master but some still aren't. E.g. the linux_64_python3.10.____cpython failure is https://github.com/scrapy/scrapy/pull/5783

We hope to release a new Scrapy version after we fix all these CI problems.

**Comment by holymonson** [comment]
@wRAR Or you could merge this and clean those restriction in next release?

**Pull request merged**
